### ISSUE TITLE
"File not found" when connected

### ISSUE THREAD

**Issue by masterjuggler** [Saur0o0n/PIDKiln#31]
I just went through the installation process on my esp32-wroom-32e. Everything compiled and uploaded without issue on the latest arduino ide. When I connect to the resulting "PIDKiln_AP" and enter the default ip 192.168.10.1 into a browser all I get is a blank page that says "file not found"

Am I just not connecting to it correctly? I didn't see anything on the wiki that mentions another way.

**Comment by Saur0o0n** [comment]
Seems like did not upload the data to your Esp SPIFFS or you put something strange in URL after the IP address.

**Comment by masterjuggler** [comment]
Alright, I finally managed to figure it out. It doesn't seem like arduino ide 2.0.0 has no support for plugins like esp32fs, so I had to grab 1.8.19 and that worked.
