### ISSUE TITLE
Changing PIN for MAX31855

### ISSUE THREAD

**Issue by astern1** [Saur0o0n/PIDKiln#37]
Hi,

I can not use PIN14 anymore because it is broken on my test WROVER.
I checked but it seems the used pins are hardcoded in the MAX31855 library, correct?

Is there a possibility to change it or maybe better question: where can ich change it, couldn't find it.

P.S.: tried wit Adafruit and the MAX Example, using 
// Example creating a thermocouple instance with software SPI on any three
// digital IO pins.
#define MAXDO   12
#define MAXCS   27
#define MAXCLK  13

worked so I would like to change it in PIDKiln

Thanks

**Comment by Saur0o0n** [comment]
On esp32 chip you have 2 hardware SPI buses - so you can't change it's pin freely (it's mentioned in PIDKiln docs). PIDKiln uses 2 spi's - one for the LCD, another for MAX boards. You could change it to software SPI - but  you would have to do it on your own.
