### ISSUE TITLE
Adding programs

### ISSUE THREAD

**Issue by codilau** [Saur0o0n/PIDKiln#39]
Hi, I can't find a way to either edit or create a new program in either the LCD ui or the web UI.
Am I missing something or the only way to do this is to edit on a different system and upload?
Thanks!

**Comment by Saur0o0n** [comment]
Hi, yes you can only upload new programs - there is no real edit mode. Somehow I haven't had need to edit it online.
https://github.com/Saur0o0n/pidkiln/wiki/Program-structure
