### ISSUE TITLE
Cannot compile: redefinition of 'class IPv6Address

### ISSUE THREAD

**Issue by videobuff** [Saur0o0n/PIDKiln#41]
Cannot compile

System: ESP-WROOM-32
Arduino on line IDE

Reinstalled new development with Arduino online coding.
Imported the sketch.
I get errors complaining "redefinition of 'class IPv6Address"

```
In file included from /home/builder/Arduino/libraries/ethersia_2_4_0/src/IPv6Packet.h:11,
from /home/builder/Arduino/libraries/ethersia_2_4_0/src/UDPSocket.h:10,
from /home/builder/Arduino/libraries/ethersia_2_4_0/src/Syslog.h:9,
from /tmp/437171178/PIDKiln/PIDKiln.h:2,
from /tmp/437171178/PIDKiln/PIDKiln.ino:35:
/home/builder/Arduino/libraries/ethersia_2_4_0/src/IPv6Address.h:27:7: error: redefinition of 'class IPv6Address'
class IPv6Address {
```

**Comment by Saur0o0n** [comment]
It looks like you should uninstall that ethersia library.

**Comment by videobuff** [comment]
I will try to do so but so far it is not listed in the IDE. I  went back to version 1.8.9 I believe an that one compilesVerstuurd vanaf mijn telefoonOp 10 jul. 2023 om 09:43 heeft Adrian Siemieniak ***@***.***> het volgende geschreven:﻿
It looks like you should uninstall that ethersia library.
