### ISSUE TITLE
Using more high temperature s-type thermocouple

### ISSUE THREAD

**Issue by Tkachlab** [Saur0o0n/PIDKiln#46]
Hello. Can i use a s-type thermocouple with max31855sasa chip? Do i need to modify code?. Thanks

**Comment by Saur0o0n** [comment]
Hi, the library used to handle max31855 chip states it works only with K type probes (https://github.com/enjoyneering/MAX31855) - so as long, as you would be able to modify this library to work with other thermocouples, PIDKiln wouldn't care what type it is.
