### ISSUE TITLE
ESP32-WROOM Compatibility

### ISSUE THREAD

**Issue by thomasfla** [Saur0o0n/PIDKiln#5]
Hello, thanks for this amazing code. I was working on the exact same thing and came across your code just in time!

I have all the required components except that I only have ESP32-Wroom based dev board instead of Wrover.
I wanted to know what the PSRAM is used for in your code and how difficult it would be to adapt it to not use it.

Best,
T.

**Comment by Saur0o0n** [comment]
Hi, there is already some information on this topic in [here](https://github.com/Saur0o0n/PIDKiln/issues/2#issuecomment-613921578) - it shouldn't be hard to convert the code.

**Comment by thomasfla** [comment]
Wanderfull, thanks.
