### ISSUE TITLE
How to change time to local

### ISSUE THREAD

**Issue by leon-Glitchking** [Saur0o0n/PIDKiln#6]
Forgive me if this is simple but I cannot figure out how to set time time to my local time (Sydney Australia).
The only option I can see is offset from GMT however it has a maximum of 1 hour (3600 seconds) when I need 10/11 hours

How to I set the time to local?

**Comment by Saur0o0n** [comment]
Hi,
You have in etc/pidkiln.conf section responsible for time settings
```
# Time offset (+/-) comparing to GMT time and daylight change if exists
GMT_Offset_sec = 3600
Daylight_Offset_sec = 3600
```
The GMT_Offset_sec is long type (-2147483648 to 2147483647) - so you can set 11*-3600=-39600 according to your time zone offset.
